#!/bin/bash

if [[ -z $1 ]]; then
    gpu=1
else
    gpu=$1
fi

if [[ -z $2 ]]; then
    n=1
else
    n=$2
fi

if [[ -z $3 ]]; then
    alpha=0
else
    alpha=$3
fi

model=MHCNN
dir=data/comparison_all/$model

while read seed; do
    if [[ $n == 0 ]]; then
        break
    fi
    if ! grep -q $seed $dir/${model}_mfcc_all.metric; then
        if [[ ! -d $dir/$seed ]]; then
            echo $dir/$seed
            python train.py --epochs 50 -m $model --batch_size 32 --alpha $alpha --lr_schedule step --learning_rate 0.001 --optimizer adam -f mfcc --segment 2 --train_overlap 1  -d $dir/$seed -g $gpu --seed $seed --impro_or_script all
            n=$[n-1]
        fi
    fi
done < seeds.txt
